// Manifest of hazard symbols sourced from ISO 7010 (Wikimedia Commons).
// Each entry references an SVG in public/symbols/; symbols.js fetches and
// base64-caches them at startup so the embedded <image> tags stay
// self-contained for PNG export. `kind` drives the category grouping in the
// symbol picker (see PICTO_GROUPS in App.jsx).
//
// W = warning (yellow triangle), P = prohibition (red circle/slash),
// M = mandatory (blue circle), E = safe condition (green), F = fire (red).
// The original 18 keep their friendly ids (e.g. `bolt`) so existing saved
// designs/presets keep resolving; newer additions are keyed by ISO code.

export const PICTOGRAMS = {
  // ---------- Warning (W) ----------
  exclamation: { name: 'General hazard',        file: 'W001.svg', code: 'W001', kind: 'warning' },
  W002:        { name: 'Explosive material',    file: 'W002.svg', code: 'W002', kind: 'warning' },
  radiation:   { name: 'Radioactive',           file: 'W003.svg', code: 'W003', kind: 'warning' },
  laser:       { name: 'Laser beam',            file: 'W004.svg', code: 'W004', kind: 'warning' },
  W005:        { name: 'Non-ionizing radiation', file: 'W005.svg', code: 'W005', kind: 'warning' },
  W006:        { name: 'Magnetic field',        file: 'W006.svg', code: 'W006', kind: 'warning' },
  W007:        { name: 'Floor obstacle',        file: 'W007.svg', code: 'W007', kind: 'warning' },
  fall:        { name: 'Fall hazard',           file: 'W008.svg', code: 'W008', kind: 'warning' },
  biohazard:   { name: 'Biological hazard',     file: 'W009.svg', code: 'W009', kind: 'warning' },
  W010:        { name: 'Low temperature',       file: 'W010.svg', code: 'W010', kind: 'warning' },
  slip:        { name: 'Slippery surface',      file: 'W011.svg', code: 'W011', kind: 'warning' },
  bolt:        { name: 'Electrical hazard',     file: 'W012.svg', code: 'W012', kind: 'warning' },
  W013:        { name: 'Guard dog',             file: 'W013.svg', code: 'W013', kind: 'warning' },
  forklift:    { name: 'Industrial truck',      file: 'W014.svg', code: 'W014', kind: 'warning' },
  W015:        { name: 'Overhead load',         file: 'W015.svg', code: 'W015', kind: 'warning' },
  skull:       { name: 'Toxic',                 file: 'W016.svg', code: 'W016', kind: 'warning' },
  hot:         { name: 'Hot surface',           file: 'W017.svg', code: 'W017', kind: 'warning' },
  W018:        { name: 'Automatic start-up',    file: 'W018.svg', code: 'W018', kind: 'warning' },
  W019:        { name: 'Crushing hazard',       file: 'W019.svg', code: 'W019', kind: 'warning' },
  W020:        { name: 'Overhead obstacle',     file: 'W020.svg', code: 'W020', kind: 'warning' },
  flame:       { name: 'Flammable',             file: 'W021.svg', code: 'W021', kind: 'warning' },
  W022:        { name: 'Sharp element',         file: 'W022.svg', code: 'W022', kind: 'warning' },
  corrosive:   { name: 'Corrosive',             file: 'W023.svg', code: 'W023', kind: 'warning' },
  crush:       { name: 'Crushing of hands',     file: 'W024.svg', code: 'W024', kind: 'warning' },
  W025:        { name: 'Counter-rotating rollers', file: 'W025.svg', code: 'W025', kind: 'warning' },
  W026:        { name: 'Battery charging',      file: 'W026.svg', code: 'W026', kind: 'warning' },
  W027:        { name: 'Optical radiation',     file: 'W027.svg', code: 'W027', kind: 'warning' },
  W028:        { name: 'Oxidizing substance',   file: 'W028.svg', code: 'W028', kind: 'warning' },
  W029:        { name: 'Pressurized cylinder',  file: 'W029.svg', code: 'W029', kind: 'warning' },
  W035:        { name: 'Falling objects',       file: 'W035.svg', code: 'W035', kind: 'warning' },
  W030:        { name: 'Hand crushing (press)',  file: 'W030.svg', code: 'W030', kind: 'warning' },

  // ---------- Prohibition (P) ----------
  noEntry:     { name: 'No entry',              file: 'P001.svg', code: 'P001', kind: 'prohibition' },
  noSmoking:   { name: 'No smoking',            file: 'P002.svg', code: 'P002', kind: 'prohibition' },
  P003:        { name: 'No open flame',         file: 'P003.svg', code: 'P003', kind: 'prohibition' },
  P004:        { name: 'No thoroughfare',       file: 'P004.svg', code: 'P004', kind: 'prohibition' },
  P005:        { name: 'Not drinking water',    file: 'P005.svg', code: 'P005', kind: 'prohibition' },
  P006:        { name: 'No forklift trucks',    file: 'P006.svg', code: 'P006', kind: 'prohibition' },
  P007:        { name: 'No pacemakers',         file: 'P007.svg', code: 'P007', kind: 'prohibition' },
  P010:        { name: 'Do not touch',          file: 'P010.svg', code: 'P010', kind: 'prohibition' },
  P011:        { name: 'Do not extinguish with water', file: 'P011.svg', code: 'P011', kind: 'prohibition' },
  P013:        { name: 'No mobile phones',      file: 'P013.svg', code: 'P013', kind: 'prohibition' },
  P022:        { name: 'No eating or drinking', file: 'P022.svg', code: 'P022', kind: 'prohibition' },
  P024:        { name: 'Do not walk here',      file: 'P024.svg', code: 'P024', kind: 'prohibition' },
  P028:        { name: 'Do not wear gloves',    file: 'P028.svg', code: 'P028', kind: 'prohibition' },
  P029:        { name: 'No photography',        file: 'P029.svg', code: 'P029', kind: 'prohibition' },
  P031:        { name: 'Do not alter switch',   file: 'P031.svg', code: 'P031', kind: 'prohibition' },
  P008:        { name: 'No metallic items',     file: 'P008.svg', code: 'P008', kind: 'prohibition' },
  P009:        { name: 'No climbing',           file: 'P009.svg', code: 'P009', kind: 'prohibition' },
  P012:        { name: 'No heavy load',         file: 'P012.svg', code: 'P012', kind: 'prohibition' },
  P014:        { name: 'No metallic implants',  file: 'P014.svg', code: 'P014', kind: 'prohibition' },
  P015:        { name: 'No reaching in',        file: 'P015.svg', code: 'P015', kind: 'prohibition' },
  P016:        { name: 'Do not spray with water', file: 'P016.svg', code: 'P016', kind: 'prohibition' },
  P019:        { name: 'No stepping on surface', file: 'P019.svg', code: 'P019', kind: 'prohibition' },
  P020:        { name: 'No lift in fire',       file: 'P020.svg', code: 'P020', kind: 'prohibition' },
  P021:        { name: 'No dogs',               file: 'P021.svg', code: 'P021', kind: 'prohibition' },
  P023:        { name: 'Do not obstruct',       file: 'P023.svg', code: 'P023', kind: 'prohibition' },
  P025:        { name: 'No incomplete scaffold', file: 'P025.svg', code: 'P025', kind: 'prohibition' },
  P027:        { name: 'No lift for people',    file: 'P027.svg', code: 'P027', kind: 'prohibition' },
  P036:        { name: 'No children',           file: 'P036.svg', code: 'P036', kind: 'prohibition' },
  P039:        { name: 'No hot works',          file: 'P039.svg', code: 'P039', kind: 'prohibition' },
  P080:        { name: 'No unauthorized access', file: 'P080.svg', code: 'P080', kind: 'prohibition' },
  P081:        { name: 'Do not cover appliance', file: 'P081.svg', code: 'P081', kind: 'prohibition' },

  // ---------- Mandatory (M) ----------
  M001:        { name: 'General mandatory',     file: 'M001.svg', code: 'M001', kind: 'mandatory' },
  M002:        { name: 'Refer to manual',       file: 'M002.svg', code: 'M002', kind: 'mandatory' },
  ears:        { name: 'Hearing protection',    file: 'M003.svg', code: 'M003', kind: 'mandatory' },
  glasses:     { name: 'Eye protection',        file: 'M004.svg', code: 'M004', kind: 'mandatory' },
  M005:        { name: 'Connect earth ground',  file: 'M005.svg', code: 'M005', kind: 'mandatory' },
  M008:        { name: 'Wear foot protection',  file: 'M008.svg', code: 'M008', kind: 'mandatory' },
  M009:        { name: 'Wear protective gloves', file: 'M009.svg', code: 'M009', kind: 'mandatory' },
  M010:        { name: 'Wear protective clothing', file: 'M010.svg', code: 'M010', kind: 'mandatory' },
  M013:        { name: 'Wear face shield',      file: 'M013.svg', code: 'M013', kind: 'mandatory' },
  hardHat:     { name: 'Head protection',       file: 'M014.svg', code: 'M014', kind: 'mandatory' },
  M015:        { name: 'Wear hi-vis clothing',  file: 'M015.svg', code: 'M015', kind: 'mandatory' },
  M016:        { name: 'Wear a mask',           file: 'M016.svg', code: 'M016', kind: 'mandatory' },
  M017:        { name: 'Wear respiratory protection', file: 'M017.svg', code: 'M017', kind: 'mandatory' },
  M018:        { name: 'Wear safety harness',   file: 'M018.svg', code: 'M018', kind: 'mandatory' },
  M026:        { name: 'Wear protective apron', file: 'M026.svg', code: 'M026', kind: 'mandatory' },
  M006:        { name: 'Disconnect mains plug', file: 'M006.svg', code: 'M006', kind: 'mandatory' },
  M007:        { name: 'Opaque eye protection', file: 'M007.svg', code: 'M007', kind: 'mandatory' },
  M011:        { name: 'Wash your hands',       file: 'M011.svg', code: 'M011', kind: 'mandatory' },
  M012:        { name: 'Use handrail',          file: 'M012.svg', code: 'M012', kind: 'mandatory' },
  M019:        { name: 'Wear welding mask',     file: 'M019.svg', code: 'M019', kind: 'mandatory' },
  M020:        { name: 'Wear safety belts',     file: 'M020.svg', code: 'M020', kind: 'mandatory' },
  M021:        { name: 'Disconnect for maintenance', file: 'M021.svg', code: 'M021', kind: 'mandatory' },
  M056:        { name: 'Ventilate before entering', file: 'M056.svg', code: 'M056', kind: 'mandatory' },
  M057:        { name: 'Continuous ventilation', file: 'M057.svg', code: 'M057', kind: 'mandatory' },
  M058:        { name: 'Entry with supervisor', file: 'M058.svg', code: 'M058', kind: 'mandatory' },
  M059:        { name: 'Wear laboratory coat',  file: 'M059.svg', code: 'M059', kind: 'mandatory' },

  // ---------- Safe condition (E) ----------
  E001:        { name: 'Emergency exit (left)', file: 'E001.svg', code: 'E001', kind: 'safe' },
  E002:        { name: 'Emergency exit (right)', file: 'E002.svg', code: 'E002', kind: 'safe' },
  E003:        { name: 'First aid',             file: 'E003.svg', code: 'E003', kind: 'safe' },
  E004:        { name: 'Emergency telephone',   file: 'E004.svg', code: 'E004', kind: 'safe' },
  E007:        { name: 'Assembly point',        file: 'E007.svg', code: 'E007', kind: 'safe' },
  E010:        { name: 'Defibrillator (AED)',   file: 'E010.svg', code: 'E010', kind: 'safe' },
  E011:        { name: 'Eyewash station',       file: 'E011.svg', code: 'E011', kind: 'safe' },
  E012:        { name: 'Safety shower',         file: 'E012.svg', code: 'E012', kind: 'safe' },
  E013:        { name: 'Stretcher',             file: 'E013.svg', code: 'E013', kind: 'safe' },
  E015:        { name: 'Drinking water',        file: 'E015.svg', code: 'E015', kind: 'safe' },
  E008:        { name: 'Break to obtain access', file: 'E008.svg', code: 'E008', kind: 'safe' },
  E009:        { name: 'Doctor',                file: 'E009.svg', code: 'E009', kind: 'safe' },
  E018:        { name: 'Turn anticlockwise to open', file: 'E018.svg', code: 'E018', kind: 'safe' },
  E019:        { name: 'Turn clockwise to open', file: 'E019.svg', code: 'E019', kind: 'safe' },
  E020:        { name: 'Emergency stop button', file: 'E020.svg', code: 'E020', kind: 'safe' },

  // ---------- Fire equipment (F) ----------
  F001:        { name: 'Fire extinguisher',     file: 'F001.svg', code: 'F001', kind: 'fire' },
  F002:        { name: 'Fire hose reel',        file: 'F002.svg', code: 'F002', kind: 'fire' },
  F003:        { name: 'Fire ladder',           file: 'F003.svg', code: 'F003', kind: 'fire' },
  F004:        { name: 'Firefighting equipment', file: 'F004.svg', code: 'F004', kind: 'fire' },
  F005:        { name: 'Fire alarm call point', file: 'F005.svg', code: 'F005', kind: 'fire' },
  F006:        { name: 'Fire emergency telephone', file: 'F006.svg', code: 'F006', kind: 'fire' },
  F007:        { name: 'Fire protection door',  file: 'F007.svg', code: 'F007', kind: 'fire' },
  F016:        { name: 'Fire blanket',          file: 'F016.svg', code: 'F016', kind: 'fire' },
  F017:        { name: "Firefighters' lift",    file: 'F017.svg', code: 'F017', kind: 'fire' },

  // ---------- GHS chemical hazard (diamond) ----------
  GHS01:       { name: 'Explosive',             file: 'GHS01.svg', code: 'GHS01', kind: 'ghs' },
  GHS02:       { name: 'Flammable',             file: 'GHS02.svg', code: 'GHS02', kind: 'ghs' },
  GHS03:       { name: 'Oxidizing',             file: 'GHS03.svg', code: 'GHS03', kind: 'ghs' },
  GHS04:       { name: 'Gas under pressure',    file: 'GHS04.svg', code: 'GHS04', kind: 'ghs' },
  GHS05:       { name: 'Corrosive',             file: 'GHS05.svg', code: 'GHS05', kind: 'ghs' },
  GHS06:       { name: 'Acute toxicity',        file: 'GHS06.svg', code: 'GHS06', kind: 'ghs' },
  GHS07:       { name: 'Harmful / irritant',    file: 'GHS07.svg', code: 'GHS07', kind: 'ghs' },
  GHS08:       { name: 'Health hazard',         file: 'GHS08.svg', code: 'GHS08', kind: 'ghs' },
  GHS09:       { name: 'Environmental hazard',  file: 'GHS09.svg', code: 'GHS09', kind: 'ghs' },

  // ---------- Public information (ISO 7001) ----------
  PF001: { name: 'Information',        file: 'PF001.svg', code: 'PF 001', kind: 'info' },
  PF002: { name: 'Hospital',           file: 'PF002.svg', code: 'PF 002', kind: 'info' },
  PF003: { name: 'Toilets',            file: 'PF003.svg', code: 'PF 003', kind: 'info' },
  PF004: { name: 'Toilets (men)',      file: 'PF004.svg', code: 'PF 004', kind: 'info' },
  PF005: { name: 'Toilets (women)',    file: 'PF005.svg', code: 'PF 005', kind: 'info' },
  PF007: { name: 'Drinking water',     file: 'PF007.svg', code: 'PF 007', kind: 'info' },
  PF015: { name: 'Smoking area',       file: 'PF015.svg', code: 'PF 015', kind: 'info' },
  PF017: { name: 'Telephone',          file: 'PF017.svg', code: 'PF 017', kind: 'info' },
  PF019: { name: 'Lift',               file: 'PF019.svg', code: 'PF 019', kind: 'info' },
  PF020: { name: 'Escalator',          file: 'PF020.svg', code: 'PF 020', kind: 'info' },
  PF021: { name: 'Stairs',             file: 'PF021.svg', code: 'PF 021', kind: 'info' },
  PF023: { name: 'Baby care',          file: 'PF023.svg', code: 'PF 023', kind: 'info' },
  PF027: { name: 'Litter bin',         file: 'PF027.svg', code: 'PF 027', kind: 'info' },
  PF028: { name: 'Entrance',           file: 'PF028.svg', code: 'PF 028', kind: 'info' },
  PF029: { name: 'Exit',               file: 'PF029.svg', code: 'PF 029', kind: 'info' },
  PF030: { name: 'Direction arrow',    file: 'PF030.svg', code: 'PF 030', kind: 'info' },
  PF044: { name: 'Doctor',             file: 'PF044.svg', code: 'PF 044', kind: 'info' },
  PF066: { name: 'Recycling',          file: 'PF066.svg', code: 'PF 066', kind: 'info' },
  PF075: { name: 'Hand dryer',         file: 'PF075.svg', code: 'PF 075', kind: 'info' },
  TF001: { name: 'Airport',            file: 'TF001.svg', code: 'TF 001', kind: 'info' },
  TF002: { name: 'Railway',            file: 'TF002.svg', code: 'TF 002', kind: 'info' },
  TF006: { name: 'Bus',                file: 'TF006.svg', code: 'TF 006', kind: 'info' },
  TF008: { name: 'Taxi',               file: 'TF008.svg', code: 'TF 008', kind: 'info' },
  TF014: { name: 'Parking',            file: 'TF014.svg', code: 'TF 014', kind: 'info' },
  TF037: { name: 'Security check',     file: 'TF037.svg', code: 'TF 037', kind: 'info' },
  TF042: { name: 'Meeting point',      file: 'TF042.svg', code: 'TF 042', kind: 'info' },
  TF044: { name: 'EV charging',        file: 'TF044.svg', code: 'TF 044', kind: 'info' },
  BP001: { name: 'Quiet please',       file: 'BP001.svg', code: 'BP 001', kind: 'info' },
  BP008: { name: 'Surveillance camera', file: 'BP008.svg', code: 'BP 008', kind: 'info' },
  CF001: { name: 'Restaurant',         file: 'CF001.svg', code: 'CF 001', kind: 'info' },
  CF005: { name: 'Cash / ATM',         file: 'CF005.svg', code: 'CF 005', kind: 'info' },
  CF007: { name: 'Pharmacy',           file: 'CF007.svg', code: 'CF 007', kind: 'info' },
  CF018: { name: 'Wi-Fi',              file: 'CF018.svg', code: 'CF 018', kind: 'info' },
  AC001: { name: 'Wheelchair access',  file: 'AC001.svg', code: 'AC 001', kind: 'info' },
};
